version: '3.4'

services:
  medium-chat-backend:
    build:
      context: .
      target: development
    volumes:
      - ./src:/medium-chat-backend/src
    ports:
      - $PORT:$PORT
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/medium-chat-backend
    links:
      - mongo

  mongo:
    image: mongo:4.2.0
    ports:
      - 27017:27017